#!/usr/bin/env python3
"""Diarization bake-off: convert each arm's native output and score it against the gold.

    python3 scripts/diarization_bakeoff.py convert --format rttm X.rttm --out X_turns.json
        -> one arm's native output as the schema's ``speaker_turns``
    python3 scripts/diarization_bakeoff.py score GOLD_labels.json --gold-map SPEAKER_01=L,SPEAKER_00=S \\
        transcripts/bakeoff/<stem>/<arm>/run1/provenance.json [...] --out-dir DIR --json FILE
        -> every arm scored through the same stage 2 and the same scorer, and the bar

Pre-registered in docs/diarization_bakeoff_plan.md, which fixes the arms, the
data path, the speaker-map rule, the metrics and the bar. This file implements
that plan; a change to anything in it after the arms have run is post-hoc.

**The data path.** The gold's raw JSON keeps its ``words`` and its
``secondary_stream``; only ``speaker_turns`` (and the ``diarization`` block that
describes them) is replaced by an arm's output, in a *copy* written to
``--out-dir`` (D3: the original record is never rewritten). Stage 2 is then the
render the gold was labeled on -- the lecture profile's stream, ``assign`` plus
``smooth`` at their defaults -- regenerated by ``diarization_labels.build``, so
the diarizer is the only thing that varies.

**The truth** is derived once, from the gold, exactly as
``score_diarization.py`` derives it (the gold's own render, its verdicts and
markers, and ``--gold-map``, the map the gold was scored with). It is a speaker
per word, and the words are the same for every arm.

**An arm's boundaries** are its own rendered label changes. Each gets a verdict
from the truth: ``real`` where the true speaker changes at that word,
``spurious`` where it does not, ``unsure`` where either side is unknown. That is
the gold's convention (diarization_repair_plan.md §1.7, answer 3) read off the
truth, so the gold's stored turns put through this path must reproduce the
scorer's own numbers exactly. ``score`` checks this first and refuses
otherwise (the identity check).

**The speaker map** for an arm is not given: it is computed from the gold, by
the same rule for every arm (``map_labels``): the optimal one-to-one pairing of
labels with gold identities (the DER convention), then every leftover label
folded into the identity it shares the most words with.

Pure Python, no model, no dependencies beyond stage 2 and the scorer. The
outputs hold counts, labels, word indices and times, never transcript text;
the raw-JSON copies written to ``--out-dir`` do hold text, so point it into
``transcripts/`` (gitignored).

Exit codes: 0 ok; 2 refused (a malformed native output, a provenance file whose
output or audio does not match, a gold that fails the identity check, an arm
whose render does not cover the gold's words).
"""

from __future__ import annotations

import argparse
import copy
import hashlib
import json
import math
import os
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional, Sequence, Tuple

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "scripts"))

import diarization_labels as dl  # noqa: E402
import score_diarization as sd  # noqa: E402
from pipeline import schema  # noqa: E402

PROVENANCE_FORMAT = 1
IDENTITY_ORDER = ("L", "S") + tuple(f"S{k}" for k in range(2, 10))
STORED_ARM = "community1@stored"

# The pre-registered bar (plan §5). Relative to the community-1 baseline, so the
# same rule applies unchanged to PSY498 once it is labeled.
BAR = {
    "primary_max_share_of_baseline": 0.5,    # student words under the instructor: at most half
    "high_harm_runs_max_share_of_baseline": 0.5,
    "accuracy_max_drop": 0.010,              # per-word accuracy: at most 1.0 point below
    "close_call_words": 5,                   # two passing arms this close are a tie
}


class Refused(Exception):
    """An input this script will not score; the message says why."""


# ------------------------------------------------------------ converters ----

def _turn(start: float, end: float, speaker: str, where: str) -> Dict[str, Any]:
    if not (math.isfinite(start) and math.isfinite(end)):
        raise Refused(f"{where}: non-finite time")
    if start < 0 or end < start:
        raise Refused(f"{where}: bad interval {start}..{end}")
    if not speaker:
        raise Refused(f"{where}: empty speaker label")
    return {"start": start, "end": end, "speaker": speaker}


def parse_rttm(text: str) -> List[Dict[str, Any]]:
    """NIST RTTM ``SPEAKER`` lines: ``SPEAKER file chnl tbeg tdur ortho stype name conf slat``.

    pyannote writes exactly ten fields (``Annotation.to_rttm``); a line that is
    not ten fields, not ``SPEAKER``, or names a second file is refused rather
    than skipped, because a silently dropped turn is a wrong score.
    """
    turns, files = [], set()
    for n, raw in enumerate(text.splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        f = line.split()
        if len(f) != 10 or f[0] != "SPEAKER":
            raise Refused(f"rttm line {n}: expected 10 fields starting with SPEAKER, got {len(f)}")
        files.add(f[1])
        try:
            onset, dur = float(f[3]), float(f[4])
        except ValueError:
            raise Refused(f"rttm line {n}: onset/duration are not numbers") from None
        if dur < 0:
            raise Refused(f"rttm line {n}: negative duration")
        turns.append(_turn(onset, round(onset + dur, 6), f[7], f"rttm line {n}"))
    if len(files) > 1:
        raise Refused(f"rttm names {len(files)} files; one arm output is one recording")
    return turns


# NeMo's own formatter (speaker_utils.generate_diarization_output_lines at the
# pinned commit): f"{start:.3f} {end:.3f} speaker_{int(spk_idx)}".
NEMO_LINE_RE = re.compile(r"^(\d+\.\d{3}) (\d+\.\d{3}) (speaker_\d+)$")


def parse_nemo_segments(text: str) -> List[Dict[str, Any]]:
    """``SortformerEncLabelModel.diarize`` output for one file, one segment per line."""
    turns = []
    for n, raw in enumerate(text.splitlines(), 1):
        if not raw.strip():
            continue
        m = NEMO_LINE_RE.match(raw.strip())
        if not m:
            raise Refused(f"nemo segments line {n}: expected 'START END speaker_N' with 3 decimals")
        turns.append(_turn(float(m.group(1)), float(m.group(2)), m.group(3), f"nemo segments line {n}"))
    return turns


def parse_turns_json(text: str) -> List[Dict[str, Any]]:
    """A JSON list of ``{start, end, speaker}``: pyannote's Annotation iterated at full precision."""
    try:
        data = json.loads(text)
    except json.JSONDecodeError as exc:
        raise Refused(f"turns json: {exc}") from None
    if not isinstance(data, list):
        raise Refused("turns json: expected a list")
    turns = []
    for n, t in enumerate(data):
        if not isinstance(t, dict) or set(t) != {"start", "end", "speaker"}:
            raise Refused(f"turns json [{n}]: expected exactly start, end, speaker")
        if not isinstance(t["speaker"], str):
            raise Refused(f"turns json [{n}]: speaker must be a string")
        try:
            turns.append(_turn(float(t["start"]), float(t["end"]), t["speaker"], f"turns json [{n}]"))
        except (TypeError, ValueError):
            raise Refused(f"turns json [{n}]: start/end are not numbers") from None
    return turns


FORMATS: Dict[str, Callable[[str], List[Dict[str, Any]]]] = {
    "rttm": parse_rttm,
    "nemo-segments": parse_nemo_segments,
    "turns-json": parse_turns_json,
}


def convert(text: str, fmt: str) -> List[Dict[str, Any]]:
    """Native output -> schema ``speaker_turns``, sorted by (start, end, speaker)."""
    if fmt not in FORMATS:
        raise Refused(f"unknown format {fmt!r}; known: {', '.join(FORMATS)}")
    return sorted(FORMATS[fmt](text), key=lambda t: (t["start"], t["end"], t["speaker"]))


# ------------------------------------------------------------- the arms -----

def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


@dataclass
class Arm:
    name: str                       # the arm, e.g. "diarizen"
    run: str                        # "run1", "run2", or "stored"
    turns: List[Dict[str, Any]]
    provenance: Dict[str, Any]
    source: str                     # where the turns came from

    @property
    def key(self) -> str:
        return f"{self.name}/{self.run}"


def load_arm(prov_path: Path, audio_sha256: str) -> Arm:
    """An arm run as ``hpc/bakeoff/run_arm.py`` recorded it; refused on any mismatch."""
    try:
        prov = json.loads(prov_path.read_text())
    except (OSError, json.JSONDecodeError) as exc:
        raise Refused(f"{prov_path}: {exc}") from None
    if prov.get("bakeoff_format") != PROVENANCE_FORMAT:
        raise Refused(f"{prov_path}: bakeoff_format is {prov.get('bakeoff_format')!r}, expected {PROVENANCE_FORMAT}")
    for key in ("arm", "run", "audio", "model", "package", "native_output", "performance"):
        if key not in prov:
            raise Refused(f"{prov_path}: missing {key!r}")
    if prov["audio"].get("sha256") != audio_sha256:
        raise Refused(f"{prov_path}: the arm ran on audio {prov['audio'].get('sha256')}, "
                      f"not the gold's {audio_sha256}")
    out = prov["native_output"]
    native = prov_path.parent / out["path"]
    if not native.is_file():
        raise Refused(f"{prov_path}: native output {native} not found")
    if sha256_file(native) != out.get("sha256"):
        raise Refused(f"{native}: sha256 differs from the one its provenance recorded")
    turns = convert(native.read_text(), out.get("format", ""))
    if not turns:
        raise Refused(f"{native}: no turns")
    return Arm(name=prov["arm"], run=prov["run"], turns=turns, provenance=prov, source=str(native))


def swap_turns(doc: Dict[str, Any], arm: Arm) -> Dict[str, Any]:
    """A copy of the record with only the diarizer's output replaced (D3: never the original)."""
    new = copy.deepcopy(doc)
    p = arm.provenance
    new["speaker_turns"] = [dict(t) for t in arm.turns]
    new["diarization"] = {
        "model_id": (p.get("model") or {}).get("id"),
        "revision": (p.get("model") or {}).get("revision"),
        "package": p.get("package"),
        "params": (p.get("call") or {}).get("params"),
        "bakeoff": {"arm": arm.name, "run": arm.run, "native_output": arm.source},
    }
    new["warnings"] = list(new.get("warnings") or []) + [
        f"diarization bake-off copy: speaker_turns are arm {arm.key} ({len(arm.turns)} turns); "
        f"words are the original record's (audio sha256 {doc['source']['audio_sha256']})"]
    problems = schema.validate(new)
    if problems:
        raise Refused(f"{arm.key}: the swapped copy fails schema v1: {problems[:3]}")
    return new


def arm_stream(doc: Dict[str, Any], label: str, sha: str) -> Tuple[sd.Stream, List[dl.Boundary]]:
    """The gold's render, with this record's turns: lecture stream, assign + smooth."""
    sheet = dl.build(doc, label, sha)
    words = [(t.lid, w) for t in sheet.text.values() for w in t.words]
    pos = {w.i: k for k, (_, w) in enumerate(words)}
    stream = sd.Stream(index=[w.i for _, w in words], labels=[w.speaker for _, w in words],
                       line_of=[lid for lid, _ in words], start=[w.start for _, w in words],
                       offset=sheet.offset, boundary_at={pos[b.word_i]: b.bid for b in sheet.boundaries})
    return stream, sheet.boundaries


def changed(truth: Sequence[Optional[str]], p: int) -> Optional[bool]:
    """Does the true speaker change entering word p? ``score_diarization.score``'s rule, verbatim."""
    if p == 0 or truth[p - 1] is None or truth[p] is None:
        return None
    if truth[p - 1] == sd.UNKNOWN_WHO and truth[p] == sd.UNKNOWN_WHO:
        return None
    return truth[p] != truth[p - 1]


def derived_labels(stream: sd.Stream, boundaries: List[dl.Boundary],
                   truth: Sequence[Optional[str]]) -> Dict[str, Any]:
    """Verdicts for an arm's own boundaries, read off the truth (the gold's convention)."""
    pos = {i: k for k, i in enumerate(stream.index)}
    out = []
    for b in boundaries:
        p = pos[b.word_i]
        c = changed(truth, p)
        verdict = "unsure" if c is None else "real" if c else "spurious"
        out.append({"id": b.bid, "word_i": b.word_i, "from": b.frm, "to": b.to, "verdict": verdict,
                    "who": truth[p] if verdict == "real" else ""})
    return {"complete": True, "boundaries": out, "markers": []}


# ------------------------------------------------------- the speaker map ----

@dataclass
class MapResult:
    speaker_map: Dict[str, str]
    paired: Dict[str, str]                    # the one-to-one part
    folded: Dict[str, str]                    # leftover labels, folded by majority
    words_in_folded: int
    counts: Dict[str, Dict[str, int]] = field(default_factory=dict)


def map_labels(labels: Sequence[Optional[str]], truth: Sequence[Optional[str]]) -> MapResult:
    """The pre-registered speaker-map rule (plan §3), the same for every arm.

    1. Count, over scored words (truth known and not ``?``), the words each
       rendered label shares with each gold identity.
    2. Pair labels with identities one to one so the shared words are
       maximal, using only pairs that share at least one word (the DER
       convention, as ``pyannote.metrics`` maps hypotheses to references).
       Exact, by dynamic programming over identity subsets. Ties go to the
       assignment that is first in label order, identities ordered L, S,
       S2..S9.
    3. Every label left over is folded into the identity it shares the most
       words with (ties in the same identity order; a label with no scored
       word goes to L). This is what the render-time speaker map allows: two
       labels may map to one name.
    """
    counts: Dict[str, Dict[str, int]] = {}
    for lab, who in zip(labels, truth):
        if lab is None:
            continue
        row = counts.setdefault(lab, {})
        if who is not None and who != sd.UNKNOWN_WHO:
            row[who] = row.get(who, 0) + 1
    ids = [w for w in IDENTITY_ORDER if any(w in row for row in counts.values())]
    k, none = len(ids), len(ids)
    labs = sorted(counts)
    best: Dict[int, Tuple[int, Tuple[int, ...]]] = {0: (0, ())}
    for lab in labs:
        nxt: Dict[int, Tuple[int, Tuple[int, ...]]] = {}
        for mask, (tot, asg) in best.items():
            options = [(none, 0)] + [(j, counts[lab].get(ids[j], 0)) for j in range(k)
                                     if not mask >> j & 1 and counts[lab].get(ids[j], 0) > 0]
            for j, gain in options:
                m2 = mask if j == none else mask | 1 << j
                cand = (tot + gain, asg + (j,))
                cur = nxt.get(m2)
                if cur is None or cand[0] > cur[0] or (cand[0] == cur[0] and cand[1] < cur[1]):
                    nxt[m2] = cand
        best = nxt
    _, asg = max(best.values(), key=lambda v: (v[0], tuple(-x for x in v[1])))
    paired = {lab: ids[j] for lab, j in zip(labs, asg) if j != none}
    folded = {}
    for lab in labs:
        if lab in paired:
            continue
        row = counts[lab]
        folded[lab] = min(IDENTITY_ORDER, key=lambda w: (-row.get(w, 0), IDENTITY_ORDER.index(w))) \
            if row else "L"
    in_folded = sum(1 for lab, who in zip(labels, truth)
                    if lab in folded and who is not None and who != sd.UNKNOWN_WHO)
    return MapResult(speaker_map={**paired, **folded}, paired=paired, folded=folded,
                     words_in_folded=in_folded, counts=counts)


# --------------------------------------------------------------- scoring ----

def high_harm_runs(truth: Sequence[Optional[str]], labels: Sequence[Optional[str]],
                   speaker_map: Dict[str, str]) -> Tuple[int, int]:
    """(runs, words) of student speech under an instructor-mapped label.

    A run is the scorer's error run (consecutive wrong words with one true
    speaker and one label), counted whatever its cause, so a high-harm error a
    boundary introduces (``wrong_label``) counts as well as a missed change.
    """
    shown = [speaker_map.get(lab) for lab in labels]
    runs = words = 0
    p, n = 0, len(truth)
    while p < n:
        bad = truth[p] is not None and truth[p] != sd.UNKNOWN_WHO and truth[p] != shown[p]
        if not bad:
            p += 1
            continue
        a = p
        while (p + 1 < n and truth[p + 1] == truth[a] and labels[p + 1] == labels[a]
               and truth[p + 1] != shown[p + 1]):
            p += 1
        if sd.is_student(truth[a]) and shown[a] == sd.INSTRUCTOR:
            runs += 1
            words += p - a + 1
        p += 1
    return runs, words


def unanchored_spurious(stream: sd.Stream, labels: Dict[str, Any], anchors: Sequence[int],
                        near: int) -> List[Dict[str, Any]]:
    """Spurious boundaries with no community-1 boundary within ``near`` words.

    The gold was labeled on community-1's render: its boundaries were judged
    one by one, but a change it drew no boundary for had to be found by reading
    (repair plan, Part 2 item 1, Part B). A challenger boundary the gold calls
    spurious *there* is where a change the labeler missed would hide. Listed
    for an audit by ear (plan §6); never scored, and the gold is not edited.
    """
    pos = {i: k for k, i in enumerate(stream.index)}
    starts = sorted(pos[b["word_i"]] for b in labels["boundaries"])
    out = []
    for b in labels["boundaries"]:
        p = pos[b["word_i"]]
        if b["verdict"] != "spurious" or any(abs(p - q) <= near for q in anchors):
            continue
        nxt = next((q for q in starts if q > p), len(stream.index))
        out.append({"word_i": b["word_i"], "time": dl.fmt_time(stream.start[p] or 0.0, stream.offset),
                    "label": b["to"], "words_until_next_boundary": nxt - p})
    return out


def score_stream(stream: sd.Stream, boundaries: List[dl.Boundary], truth: List[Optional[str]],
                 near: int, anchors: Sequence[int] = ()) -> Dict[str, Any]:
    """Map the arm's labels by the rule, then score with the existing scorer, unchanged."""
    m = map_labels(stream.labels, truth)
    labels = derived_labels(stream, boundaries, truth)
    r = sd.score(labels, stream, truth, m.speaker_map, near)
    audit = unanchored_spurious(stream, labels, anchors, near)
    runs, run_words = high_harm_runs(truth, stream.labels, m.speaker_map)
    pessimistic = {**m.speaker_map, **{lab: sd.INSTRUCTOR for lab in m.folded}}
    p_runs, p_words = high_harm_runs(truth, stream.labels, pessimistic)
    rendered = sorted({lab for lab in stream.labels if lab is not None})
    r["bakeoff"] = {
        "speaker_map": m.speaker_map, "paired": m.paired, "folded": m.folded,
        "words_in_folded_labels": m.words_in_folded,
        "label_identity_counts": m.counts,
        "labels_rendered": len(rendered),
        "high_harm_runs": runs, "high_harm_run_words": run_words,
        "pessimistic_fold": {"speaker_map": pessimistic, "student_as_instructor": p_words,
                             "high_harm_runs": p_runs},
        "unanchored_spurious": {"count": len(audit), "items": audit},
    }
    return r


def compare(a: Any, b: Any, path: str = "") -> List[str]:
    """Paths at which two JSON-like values differ."""
    if isinstance(a, dict) and isinstance(b, dict):
        out = []
        for k in sorted(set(a) | set(b), key=str):
            if k not in a or k not in b:
                out.append(f"{path}/{k}")
            else:
                out += compare(a[k], b[k], f"{path}/{k}")
        return out
    if isinstance(a, list) and isinstance(b, list):
        if len(a) != len(b):
            return [f"{path} (length {len(a)} vs {len(b)})"]
        out = []
        for k, (x, y) in enumerate(zip(a, b)):
            out += compare(x, y, f"{path}[{k}]")
        return out
    return [] if a == b else [path or "/"]


@dataclass
class Gold:
    labels: Dict[str, Any]
    path: Path
    source: Path
    doc: Dict[str, Any]
    stream: sd.Stream
    truth: List[Optional[str]]
    gold_map: Dict[str, str]
    reference: Dict[str, Any]       # score_diarization.score on the gold, as §1.7 ran it


def load_gold(labels_path: Path, gold_map: Dict[str, str], near: int,
              source_override: Optional[Path] = None) -> Gold:
    labels = json.loads(labels_path.read_text())
    if not labels.get("complete"):
        raise Refused("the gold is not complete; the bake-off scores only a finished sheet")
    try:
        stream = sd.rendered_stream(labels, labels_path, source_override)
    except SystemExit as exc:       # the scorer's own refusals
        raise Refused(str(exc)) from None
    unmapped = sorted({lab for lab in stream.labels if lab is not None} - set(gold_map))
    if unmapped:
        raise Refused(f"--gold-map does not say who {', '.join(unmapped)} is")
    truth = sd.derive_truth(labels, stream, gold_map)
    src_label = labels["source"]
    src = source_override or (Path(src_label) if os.path.isabs(src_label) else labels_path.parent / src_label)
    doc = schema.read(src)
    return Gold(labels=labels, path=labels_path, source=src, doc=doc, stream=stream, truth=truth,
                gold_map=gold_map, reference=sd.score(labels, stream, truth, gold_map, near))


def score_arm(gold: Gold, arm: Arm, near: int, out_dir: Optional[Path]) -> Dict[str, Any]:
    if arm.run == "stored":
        doc = gold.doc
    else:
        doc = swap_turns(gold.doc, arm)
        if out_dir is not None:
            stem = gold.source.name[:-len("_raw.json")] if gold.source.name.endswith("_raw.json") \
                else gold.source.stem
            out_dir.mkdir(parents=True, exist_ok=True)
            dest = out_dir / f"{stem}_bakeoff-{arm.name}-{arm.run}_raw.json"
            dest.write_text(json.dumps(doc, indent=1) + "\n")
    stream, boundaries = arm_stream(doc, gold.labels["source"], gold.labels["source_sha256"])
    if stream.index != gold.stream.index:
        raise Refused(f"{arm.key}: the render's words differ from the gold's; the words must be fixed")
    r = score_stream(stream, boundaries, gold.truth, near, sorted(gold.stream.boundary_at))
    speakers = sorted({t["speaker"] for t in arm.turns})
    r["arm"] = {"name": arm.name, "run": arm.run, "source": arm.source, "turns": len(arm.turns),
                "labels_raw": len(speakers),
                "model": arm.provenance.get("model"), "package": arm.provenance.get("package"),
                "call": arm.provenance.get("call"), "performance": arm.provenance.get("performance"),
                "turns_sha256": hashlib.sha256(json.dumps(arm.turns, sort_keys=True).encode()).hexdigest()}
    return r


def identity_check(gold: Gold, near: int) -> Dict[str, Any]:
    """The stored turns through the arm path must reproduce the scorer's numbers exactly."""
    stored = Arm(name="community1", run="stored", turns=list(gold.doc.get("speaker_turns") or []),
                 provenance={"model": gold.doc.get("diarization"),
                             "package": {"name": "pyannote.audio",
                                         "version": ((gold.doc.get("run") or {}).get("packages") or {})
                                         .get("pyannote.audio")}},
                 source=str(gold.source))
    r = score_arm(gold, stored, near, None)
    # Everything the scorer reports must match, the speaker map included: the
    # map rule has to reproduce the map the gold was scored with.
    mine = {k: v for k, v in r.items() if k not in ("bakeoff", "arm")}
    diff = compare(mine, gold.reference)
    if diff:
        raise Refused("identity check failed: the stored turns through the bake-off path do not "
                      f"reproduce score_diarization's numbers; first differences: {diff[:5]}")
    return r


# ------------------------------------------------------------------ bar -----

def headline(r: Dict[str, Any]) -> Dict[str, Any]:
    w, b = r["words"], r["bakeoff"]
    return {"student_as_instructor": w["student_as_instructor"], "student_words": w["student_words"],
            "share": w["student_as_instructor_share_of_student_words"],
            "high_harm_runs": b["high_harm_runs"],
            "pessimistic_student_as_instructor": b["pessimistic_fold"]["student_as_instructor"],
            "accuracy": w["accuracy"]}


def worse(a: Dict[str, Any], b: Dict[str, Any]) -> Dict[str, Any]:
    """Of two runs of one arm, the one the bar is applied to: more high-harm words, then runs,
    then lower accuracy."""
    ka = (a["words"]["student_as_instructor"], a["bakeoff"]["high_harm_runs"], -(a["words"]["accuracy"] or 0))
    kb = (b["words"]["student_as_instructor"], b["bakeoff"]["high_harm_runs"], -(b["words"]["accuracy"] or 0))
    return a if ka >= kb else b


def apply_bar(baseline: Dict[str, Any], arm: Dict[str, Any]) -> Dict[str, Any]:
    """The pre-registered bar (plan §5) for one challenger, against community-1."""
    base, x = headline(baseline), headline(arm)
    lim_words = math.floor(base["student_as_instructor"] * BAR["primary_max_share_of_baseline"])
    lim_runs = math.floor(base["high_harm_runs"] * BAR["high_harm_runs_max_share_of_baseline"])
    lim_acc = round((base["accuracy"] or 0) - BAR["accuracy_max_drop"], 4)
    checks = {
        "P1_primary": {"value": x["student_as_instructor"], "limit": lim_words,
                       "pass": x["student_as_instructor"] <= lim_words},
        "P2_primary_pessimistic_fold": {"value": x["pessimistic_student_as_instructor"], "limit": lim_words,
                                        "pass": x["pessimistic_student_as_instructor"] <= lim_words},
        "P3_high_harm_runs": {"value": x["high_harm_runs"], "limit": lim_runs,
                              "pass": x["high_harm_runs"] <= lim_runs},
        "G1_accuracy": {"value": x["accuracy"], "limit": lim_acc, "pass": (x["accuracy"] or 0) >= lim_acc},
    }
    return {"checks": checks, "pass": all(c["pass"] for c in checks.values()),
            "worse_than_baseline": x["student_as_instructor"] > base["student_as_instructor"]}


def verdict(baseline: Dict[str, Any], challengers: Dict[str, Dict[str, Any]]) -> Dict[str, Any]:
    bars = {name: apply_bar(baseline, r) for name, r in challengers.items()}
    passing = sorted((n for n, b in bars.items() if b["pass"]),
                     key=lambda n: challengers[n]["words"]["student_as_instructor"])
    if not passing:
        decision = "keep community-1"
    elif len(passing) == 1:
        decision = f"switch candidate: {passing[0]}"
    else:
        a, b = passing[0], passing[1]
        gap = challengers[b]["words"]["student_as_instructor"] - challengers[a]["words"]["student_as_instructor"]
        decision = (f"switch candidate: {a}" if gap > BAR["close_call_words"]
                    else f"close call ({a}, {b} within {BAR['close_call_words']} words): "
                         "the lower install cost decides (plan §5)")
    return {"bar": BAR, "per_arm": bars, "passing": passing, "decision": decision}


# ------------------------------------------------------------- reporting ----

def summary(result: Dict[str, Any]) -> List[str]:
    pct = lambda x: "n/a" if x is None else f"{100 * x:.1f}%"   # noqa: E731
    out = [f"identity check: passed (the stored turns reproduce score_diarization: "
           f"{result['identity']['student_as_instructor']} student words under the instructor)"]
    hdr = (f"{'arm':28} {'labels':>6} {'stu->L':>7} {'share':>6} {'pess.':>5} {'runs':>4} "
           f"{'missed':>6} {'bounds':>6} {'prec':>6} {'prec3':>6} {'acc':>6} {'audit':>5} {'secs':>7}")
    out += [hdr, "-" * len(hdr)]
    for key, r in result["arms"].items():
        w, b, bk = r["words"], r["boundaries"], r["bakeoff"]
        perf = (r["arm"].get("performance") or {})
        secs = perf.get("diarize_s")
        out.append(
            f"{key:28} {bk['labels_rendered']:>6} {w['student_as_instructor']:>7} "
            f"{pct(w['student_as_instructor_share_of_student_words']):>6} "
            f"{bk['pessimistic_fold']['student_as_instructor']:>5} {bk['high_harm_runs']:>4} "
            f"{r['missed_changes']['count']:>6} {b['total']:>6} {pct(b['precision']):>6} "
            f"{pct(b['precision_within_words'][-1]['precision'] if b['precision_within_words'] else None):>6} "
            f"{pct(w['accuracy']):>6} {bk['unanchored_spurious']['count']:>5} "
            f"{('-' if secs is None else f'{secs:.0f}'):>7}")
    for name, det in result["determinism"].items():
        out.append(f"determinism {name}: " + ("identical turns across runs" if det["identical"]
                                              else f"runs differ; the bar uses {det['scored']}"))
    v = result["verdict"]
    for name, bar in v["per_arm"].items():
        out.append(f"bar {name}: {'PASS' if bar['pass'] else 'fail'}  " + "  ".join(
            f"{k} {c['value']}/{c['limit']}{'' if c['pass'] else ' x'}" for k, c in bar["checks"].items()))
    out.append(f"decision: {v['decision']}")
    return out


# ------------------------------------------------------------------ CLI -----

def run_score(a: argparse.Namespace) -> int:
    gold_map = sd.parse_speaker_map(a.gold_map)
    gold = load_gold(Path(a.gold), gold_map, a.near, Path(a.source) if a.source else None)
    audio_sha = gold.doc["source"]["audio_sha256"]
    stored = identity_check(gold, a.near)
    arms = [load_arm(Path(p), audio_sha) for p in a.provenance]
    seen = set()
    for arm in arms:
        if arm.key in seen:
            raise Refused(f"{arm.key} is given twice")
        seen.add(arm.key)
    out_dir = Path(a.out_dir) if a.out_dir else None
    scored: Dict[str, Dict[str, Any]] = {STORED_ARM: stored}
    for arm in arms:
        scored[arm.key] = score_arm(gold, arm, a.near, out_dir)

    # One result per arm for the bar: the worse run if runs differ (plan §2).
    by_arm: Dict[str, List[str]] = {}
    for arm in arms:
        by_arm.setdefault(arm.name, []).append(arm.key)
    determinism, per_arm = {}, {}
    for name, keys in by_arm.items():
        shas = {scored[k]["arm"]["turns_sha256"] for k in keys}
        pick = scored[keys[0]]
        for k in keys[1:]:
            pick = worse(pick, scored[k])
        determinism[name] = {"runs": keys, "identical": len(shas) == 1,
                             "scored": f"{pick['arm']['name']}/{pick['arm']['run']}"}
        per_arm[name] = pick
    # The baseline is community-1 at its better: the stored turns, or a rerun if better.
    baseline = stored
    for k in by_arm.get("community1", []):
        if scored[k]["words"]["student_as_instructor"] < baseline["words"]["student_as_instructor"]:
            baseline = scored[k]
    challengers = {n: r for n, r in per_arm.items() if n != "community1"}
    result = {
        "plan": "docs/diarization_bakeoff_plan.md",
        "gold": str(gold.path), "gold_sha256": sha256_file(gold.path),
        "source": gold.labels["source"], "source_sha256": gold.labels["source_sha256"],
        "gold_map": gold_map, "near_words": a.near,
        "identity": headline(stored),
        "baseline": {"arm": f"{baseline['arm']['name']}/{baseline['arm']['run']}", **headline(baseline)},
        "arms": scored, "determinism": determinism,
        "verdict": verdict(baseline, challengers),
    }
    for ln in summary(result):
        print(ln)
    if a.json:
        Path(a.json).write_text(json.dumps(result, indent=1) + "\n")
        print(f"wrote {a.json}")
    return 0


def run_convert(a: argparse.Namespace) -> int:
    turns = convert(Path(a.input).read_text(), a.format)
    labels = sorted({t["speaker"] for t in turns})
    print(f"{len(turns)} turns, {len(labels)} labels: {', '.join(labels)}")
    if a.out:
        Path(a.out).write_text(json.dumps(turns, indent=1) + "\n")
        print(f"wrote {a.out}")
    return 0


def main(argv: Optional[List[str]] = None) -> int:
    p = argparse.ArgumentParser(description=__doc__.split("\n\n")[0],
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)
    c = sub.add_parser("convert", help="one native output -> speaker_turns")
    c.add_argument("input")
    c.add_argument("--format", required=True, choices=sorted(FORMATS))
    c.add_argument("--out", default=None, help="write the turns here as JSON")
    s = sub.add_parser("score", help="score every arm against the gold")
    s.add_argument("gold", help="the gold *_labels.json (the normalized, checked one)")
    s.add_argument("provenance", nargs="*", help="each arm run's provenance.json (run_arm.py wrote it)")
    s.add_argument("--gold-map", required=True,
                   help="the map the gold was scored with, e.g. SPEAKER_01=L,SPEAKER_00=S")
    s.add_argument("--source", default=None, help="the gold's raw JSON, if not where the labels say")
    s.add_argument("--near", type=int, default=sd.NEAR_WORDS)
    s.add_argument("--out-dir", default=None, help="write each arm's swapped raw-JSON copy here (holds text)")
    s.add_argument("--json", default=None, help="also write the numbers here")
    a = p.parse_args(argv)
    try:
        return run_score(a) if a.cmd == "score" else run_convert(a)
    except (Refused, OSError, ValueError, KeyError) as exc:
        print(f"refused: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
